### ISSUE TITLE
Best practice for simulate_nan with categorical data

### ISSUE THREAD

**Issue by Outsider565** [vanderschaarlab/hyperimpute#31]
Hi! Thank you for providing such an amazing repo:) 
I recently used this library to benchmark different imputation methods on various tables. But when it comes to the table with categorical features, like string, the simulate_nan function doesn't work. 
```
Traceback (most recent call last):
  File "/mnt/home/xxx/missval/main.py", line 45, in <module>
    datasets = get_train_test_data()
  File "/mnt/home/xxx/missval/main.py", line 34, in get_train_test_data
    x_train_masked, x_train_miss, x_train_mask = ampute(
  File "/mnt/home/xxx/xxx/missval/main.py", line 10, in ampute
    x_simulated = simulate_nan(np.asarray(x), p_miss, mechanism)
  File "/home/aiops/xxx/envs/xxx/lib/python3.9/site-packages/hyperimpute/plugins/utils/simulate.py", line 299, in simulate_nan
    mask = MAR_mask(X, p_miss, p_obs, sample_columns=sample_columns).astype(float)
  File "/home/aiops/xxx/miniconda3/envs/xxx/lib/python3.9/site-packages/hyperimpute/plugins/utils/simulate.py", line 100, in MAR_mask
    coeffs = pick_coeffs(X, idxs_obs, idxs_nas)
  File "/home/aiops/xxx/miniconda3/envs/xxx/lib/python3.9/site-packages/hyperimpute/plugins/utils/simulate.py", line 29, in pick_coeffs
    Wx = X[:, idxs_obs] @ coeffs
TypeError: can't multiply sequence by non-int of type 'float'
```
After reviewing the source code, I found out that it was not possible to fit a logistic model on categorical data.

```
# in utils/simulate.py
# Pick coefficients so that W^Tx has unit variance (avoids shrinking)
coeffs = pick_coeffs(X, idxs_obs, idxs_nas)
# Pick the intercepts to have a desired amount of missing values
intercepts = fit_intercepts(X[:, idxs_obs], coeffs, p)
```
I wonder:
1. Will simulate_nan with categorical data be supported in the future?
2. Should I use an encoding like [catboost](https://github.com/scikit-learn-contrib/category_encoders/blob/8f7628d7b0ce87128e53a53e89d3c0156b73d46e/category_encoders/cat_boost.py) to convert categorical data to the numerical data first?

**Comment by bcebere** [comment]
Hello @Outsider565 

Thank you for your feedback.

For the `simulate_nan` call, we always assumed the data was already encoded. But it would be a good feature to encode internally; thank you for the suggestion! We will include this in the next release, most likely in January.

Regarding encoding, anything like label encoding or target encoding should work fine.

**Comment by Outsider565** [comment]
Thank you for your help! I'll close this issue.
