### ISSUE TITLE
ValueError: Plugin miracle cannot be loaded

### ISSUE THREAD

**Issue by Angel-spz** [vanderschaarlab/hyperimpute#32]
Hello:
    Thank you for providing such a powerful hyperimpute for data imputation. However, when I use MIRACLE, some errors have occurred. I cannot use 'method = "miracle" ', which gave me:
     File "D:\anaconda\lib\site-packages\hyperimpute\plugins\core\base_plugin.py", line 221, in get
         raise ValueError(f"Plugin {name} cannot be loaded.")
     ValueError: Plugin miracle cannot be loaded.
Thank you!

**Comment by bcebere** [comment]
Hello @Angel-spz 

Thank you for your feedback.

The `miracle` plugin is covered by tests [here](https://github.com/vanderschaarlab/hyperimpute/blob/main/tests/imputers/test_miracle.py) and the tests are currently passing [here](https://github.com/vanderschaarlab/hyperimpute/actions/runs/3785302872).

To further investigate, please provide:
 - your OS and python version.
 - the `hyperimpute` and `miracle-imputation` versions installed by pip.

We will try to improve the error logs in the future.

**Comment by Angel-spz** [comment]
Hello!
Thank you for your reply. 

- my ‘OS’ version is ‘Windows 10’ and my ‘python’ version is ‘3.7’
- the ‘hyperimpute’ version is ‘0.1.12’ and the ‘miracle-imputation’ version is ‘0.1.4’

Looking forward to your reply!

**Comment by Angel-spz** [comment]
Hello!
Thank you for your reply. 

- my ‘OS’ version is `Windows 10` and my `python` version is `3.7`
- the `hyperimpute` version is `0.1.12` and the `miracle-imputation` version is `0.1.4`

Looking forward to your reply!

**Comment by bcebere** [comment]
And one more question: If you start a Python shell, and run just this line
```python
from miracle import MIRACLE
```

do you get any errors?

Thanks!

**Comment by Angel-spz** [comment]
I try to enable debug logging in my script but there is no log print. Besides, when I run the line
`from miracle import MIRACLE`
I get the following error：
`  File "E:/postgraduate/medical/transfer-compare-1/2.py", line 1, in <module>
    from miracle import MIRACLE
  File "D:\anaconda\lib\site-packages\miracle\__init__.py", line 6, in <module>
    from .MIRACLE import MIRACLE  # noqa: F401
  File "D:\anaconda\lib\site-packages\miracle\MIRACLE.py", line 9, in <module>
    import tensorflow.compat.v1 as tf
ModuleNotFoundError: No module named 'tensorflow.compat'` 
It seems like my version of tensorflow has some problems.

**Comment by bcebere** [comment]
OK, I will fix the logging part.

Regarding tensorflow, what version are you using?

**Comment by Angel-spz** [comment]
My tensorflow `version == 2.11.0`.

**Comment by bcebere** [comment]
This is really weird.

Side question: what name are you using for your script? "tf.compat" sometimes fails from name clashes.

**Comment by bcebere** [comment]
"tf.compat" exists in version 2.11 "https://www.tensorflow.org/api_docs/python/tf/compat".

The only related issue I found is if there is a name clash in the script's name https://stackoverflow.com/questions/72029857/no-module-named-tensorflow-compat

**Comment by Angel-spz** [comment]
For testing purposes, I simply named the script '1'. Another script named 'prepare_data_median' which uses the MIRACLE method also has this bug.

**Comment by bcebere** [comment]
Maybe there is an issue with the folder name. This looks really weird.

Just create a script `debug.py` with

```python
from miracle import MIRACLE
```

and put it in `E:`. Is that script crashing too?

**Comment by Angel-spz** [comment]
I put `debug.py` in `E:\debug`, it is also crashing.

**Comment by bcebere** [comment]
Another possibility is that somehow you import tensorflow 1

```python
import tensorflow as tf

print(tf.__version__)

```

Is this also printing "2.11"?

**Comment by Angel-spz** [comment]
It is very weird that it gave me：
`  File "E:/debug/debug.py", line 3, in <module>
    print(tf.__version__)
AttributeError: module 'tensorflow' has no attribute '__version__'`

**Comment by bcebere** [comment]
And if you replace it with

```python
print(tf.version.VERSION)
```
?

**Comment by bcebere** [comment]
I suspect you are using TF 1 somehow.

I will try to add support in MIRACLE for TF1 too.

**Comment by bcebere** [comment]
OK, I suspect you use TF1 somehow, which is only for Python 3.7.

I pushed another release for MIRACLE, to enforce TF>=2.

There are 2 options:
- Update MIRACLE and try again : `pip install miracle-imputation --force`
- Try in a conda env with Python >= 3.8 . That env will install TF2 for sure.

**Comment by Angel-spz** [comment]
I use the first method and have already solved the problem successfully! Thank you very much for your patient guidance and response!
